
services:
  luanti-server:
    image: linuxserver/luanti:latest
    container_name: vegan-wetlands-server
    restart: unless-stopped
    ports:
      - "30000:30000/udp"
    volumes:
      - ./server/config/luanti.conf:/config/.minetest/minetest.conf
      - ./server/mods/vegan_foods:/config/.minetest/games/mineclone2/mods/ITEMS/vegan_foods
      - ./server/mods/animal_sanctuary:/config/.minetest/games/mineclone2/mods/ENTITIES/animal_sanctuary
      - ./server/mods/education_blocks:/config/.minetest/games/mineclone2/mods/HELP/education_blocks
      - ./server/worlds:/config/.minetest/worlds
      - ./server/games:/config/.minetest/games
      - ./server/backups:/backups
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -tulpn | grep :30000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - luanti-network

  # Backup service opcional con n8n integration
  backup-cron:
    image: alpine:latest
    container_name: vegan-wetlands-backup
    restart: unless-stopped
    volumes:
      - ./server/worlds:/worlds:ro
      - ./server/backups:/backups
      - ./scripts:/scripts:ro
    environment:
      - TZ=America/Santiago
    command: >
      sh -c "
        apk add --no-cache dcron tar gzip &&
        echo '0 */6 * * * /scripts/backup.sh' | crontab - &&
        crond -f -d 8
      "
    depends_on:
      - luanti-server
    networks:
      - luanti-network

networks:
  luanti-network:
    driver: bridge
